In [ ]:
# Álgebra Lineal
# Análisis de Preferencia de Productos
# Supongamos que estás trabajando para una tienda online y quieres entender las preferencias de
# tus clientes en relación con cuatro categorías de productos: tecnología, moda, libros y deportes.
# Para ello, has extraído en una matriz el número de compras para cada categoría en un periodo
# determinado:

M = [
        [4, 1, 6, 2],
        [2, 8, 1, 3],
        [5, 2, 3, 9]
        ]

# donde las filas representan los diferentes clientes y las columnas representan las categorías
# respectivamente.
# Empleando esta matriz, desarrolle un algoritmo en python que:
# a) Calcule el total de compras por categoría
# b) Identifique que cliente ha comprado más unidades en total
# c) Obtenga el gasto por cliente empleando la siguiente matriz de precios por categoría 

M = [
90,
150,
50,
110,
]

In [19]:
import numpy as np

cust_purchases = np.array(
                [
                [4, 1, 6, 2], 
                [2, 8, 1, 3], 
                [5, 2, 3, 9] 
                ])

prices = np.array([90, 150, 50, 110])
print(f"Purchases {cust_purchases}")
print(f"Prices {prices}")

# a) Calcule el total de compras por categoría

def by_category(purchases):
    return purchases.sum(axis=0)

def by_customer(purchases):
    return purchases.sum(axis=1)

total_purchases = cust_purchases.dot(prices)
print(f"a) Total de compras por categoría: {by_category(cust_purchases)}")
print(f"b) Cliente que ha comprado más unidades en total: {np.argmax(by_customer(cust_purchases))}")

def customer_expense(purchases, prices):
    return purchases.dot(prices)

print(f"Calc Total de compras por categoría {customer_expense(cust_purchases, prices)}")

Purchases [[4 1 6 2]
 [2 8 1 3]
 [5 2 3 9]]
Prices [ 90 150  50 110]
a) Total de compras por categoría: [11 11 10 14]
b) Cliente que ha comprado más unidades en total: 2
Calc Total de compras por categoría [1030 1760 1890]


In [34]:
from sklearn.preprocessing import StandardScaler

# Reducción de Dimensionalidad
# Eres un científico de datos en un banco, y se te proporciona un conjunto de datos con información
# sobre los clientes. Este conjunto incluye las siguientes características: edad, salario anual, y saldo
# en cuenta. El objetivo es segmentar a los clientes para campañas de marketing más efectivas.
# Cliente Edad Salario Anual (USD) Saldo en Cuenta (USD)

# 1 25 50000 1000
# 2 30 60000 1500
# 3 35 75000 3000
# 4 40 85000 4000
# 5 45 95000 5000
# 6 50 100000 6000

# Se pide:
# • Utilizando PCA, reduce las dimensiones de este conjunto de datos a dos componentes
# principales.
# • Representa gráficamente los clientes en el nuevo espacio bidimensional y determina si es
# posible identificar segmentos distintos de clientes basados en los componentes principales.


X = np.array([
    [25, 50000, 1000],
    [30, 60000, 1500],
    [35, 75000, 3000],
    [40, 85000, 4000],
    [45, 95000, 5000],
    [50, 100000, 6000]
])
M = np.array([
    [1, 25, 50000, 1000],
    [2, 30, 60000, 1500],
    [3, 35, 75000, 3000],
    [4, 40, 85000, 4000],
    [5, 45, 95000, 5000],
    [6, 50, 100000, 6000]
])

scaler = StandardScaler()
X_std = scaler.fit_transform(X)
M_std = scaler.fit_transform(M)

print(f"Datos Estandarizados sin remover la columna del indice: \r {X_std}")
print("")
print(f"Datos Estandarizados: \r {M_std}")
print("")

# 2. Cálculo de la matriz de covarianza
cov_matrix = np.cov(X_std.T)
print(f"Matriz de Covarianza sin remover: \r {cov_matrix}")
print("")
mcov_matrix = np.cov(M_std.T)
print(f"Matriz de Covarianza: \r {mcov_matrix}")
print("")

# 3. Obtención y ordenamiento de los autovalores y autovectores
eigenvalues, eigenvectors = np.linalg.eig(mcov_matrix.T)

# # 4. Selección de las componentes principales (solo la primera)
eig_pairs = [(np.abs(eigenvalues[i]), eigenvectors[:,i]) for i in range(len(eigenvalues))]
eig_pairs.sort(key=lambda x: x[0], reverse=True)

# # 5. Transformación al nuevo componente
M_pca = M_std.dot(eig_pairs[0][1])

# print(X_pca)


 [[-1.46385011 -1.53033836 -1.35066466]umna del indice: 
 [-0.87831007 -0.97385168 -1.0712168 ]
 [-0.29277002 -0.13912167 -0.23287322]
 [ 0.29277002  0.41736501  0.3260225 ]
 [ 0.87831007  0.97385168  0.88491822]
 [ 1.46385011  1.25209502  1.44381394]]

 [[-1.46385011 -1.46385011 -1.53033836 -1.35066466]
 [-0.87831007 -0.87831007 -0.97385168 -1.0712168 ]
 [-0.29277002 -0.29277002 -0.13912167 -0.23287322]
 [ 0.29277002  0.29277002  0.41736501  0.3260225 ]
 [ 0.87831007  0.87831007  0.97385168  0.88491822]
 [ 1.46385011  1.46385011  1.25209502  1.44381394]]

 [[1.2        1.1893351  1.19448376]
 [1.1893351  1.2        1.18964393]
 [1.19448376 1.18964393 1.2       ]]

 [[1.2        1.2        1.1893351  1.19448376]
 [1.2        1.2        1.1893351  1.19448376]
 [1.1893351  1.1893351  1.2        1.18964393]
 [1.19448376 1.19448376 1.18964393 1.2       ]]

